### ISSUE TITLE
Can't get Ustreamer and Symlink to work together

### ISSUE THREAD

**Issue by BlueWings172** [pikvm/ustreamer#183]
Hello

I trying to use 2 webcams but they keep swapping video0 and video1 so I decided to use udev rules to create symlinks in addition the Ustreamer and I had working it for a while until i rebooted the Pi !!

Not sure what I did wrong and this is driving me crazy and Ustreamer is showing **No Signal** on the browser. If I don't use the symlinks, Ustreamer works.

Here is my rule with priority 99:

`SUBSYSTEM=="video4linux", ENV{ID_BUS}=="usb", ATTRS{idVendor}=="090c", ATTRS{idProduct}=="f37d", SYMLINK+="endoscope"`

The dev/endoscope does show when I run ls /dev and when I run udevadm info /dev/endoscope  I get the correct info of the webcam

Here is my docker-compose YAML file:

```
  ustreamer:
    image: mkuf/ustreamer:latest
    restart: unless-stopped
    ports:
      - 8091:8080
    devices:
      - "/dev/endoscope"
    command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/endoscope --resolution=1080x720 --format=MJPEG --desired-fps=20
```

when I run `docker-compose logs ustreamer` , I get repeated rows of the below:

```
iotstack-ustreamer-1  | -- INFO  [579.531    stream] -- Device fd=8 opened
iotstack-ustreamer-1  | -- INFO  [579.531    stream] -- Using input channel: 0
iotstack-ustreamer-1  | -- ERROR [579.531    stream] -- Can't set input channel
iotstack-ustreamer-1  | -- INFO  [579.531    stream] -- Device fd=8 closed
iotstack-ustreamer-1  | -- INFO  [579.531    stream] -- Sleeping 1 seconds before new stream init ...
```

That said, if I modify my docker-compose YAML to include `/dev/video0` instead of` /dev/endoscope` then it works.

So why Ustreamer doesn't want to play well with my symlink ?

I would appreciate any help.

thanks!
