### ISSUE TITLE
uvc 4k video stream can't scale down

### ISSUE THREAD

**Issue by dragonandy** [pikvm/ustreamer#282]
uvc 4k video stream can't scale down to 720p
the stream is crop into 720p instead of showing the full image
<img width="1322" alt="screenshot" src="https://github.com/user-attachments/assets/2c0bc18a-75eb-41b6-bc29-057c4ea15e6c">

```bash
dietpi@dietpi: sudo v4l2-ctl --list-formats --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : USB3 Video: USB3 Video
	Bus info         : usb-0000:01:00.0-2
	Driver version   : 6.1.21
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : USB3 Video: USB3 Video
	Serial           : 20210623
	Bus info         : usb-0000:01:00.0-2
	Media version    : 6.1.21
	Hardware revision: 0x00003100 (12544)
	Driver version   : 6.1.21
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : USB3 Video: USB3 Video
	Function         : V4L2 I/O
	Flags            : default
	Pad 0x01000007   : 0: Sink
	  Link 0x0200000d: from remote pad 0x100000a of entity 'Processing 2' (Video Pixel Formatter): Data, Enabled, Immutable
Priority: 2
Video input : 0 (Input 1: ok)
Format Video Capture:
	Width/Height      : 1280/720
	Pixel Format      : 'YUYV' (YUYV 4:2:2)
	Field             : None
	Bytes per Line    : 2560
	Size Image        : 1843200
	Colorspace        : sRGB
	Transfer Function : Rec. 709
	YCbCr/HSV Encoding: ITU-R 601
	Quantization      : Default (maps to Limited Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 1280, Height 720
	Default     : Left 0, Top 0, Width 1280, Height 720
	Pixel Aspect: 1/1
Selection Video Capture: crop_default, Left 0, Top 0, Width 1280, Height 720, Flags: 
Selection Video Capture: crop_bounds, Left 0, Top 0, Width 1280, Height 720, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 50.000 (50/1)
	Read buffers     : 0

User Controls

                     brightness 0x00980900 (int)    : min=0 max=100 step=1 default=50 value=50
                       contrast 0x00980901 (int)    : min=0 max=100 step=1 default=50 value=50
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=50 value=50
                            hue 0x00980903 (int)    : min=0 max=100 step=1 default=50 value=50
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'YUYV' (YUYV 4:2:2)
	[1]: 'MJPG' (Motion-JPEG, compressed)
```

```yaml
    streamer:
        forever: False
        quality: 0
        resolution:
            default: 1280x720
            available:
                - 3840x2160
                - 2560x1600
                - 1920x1080
                - 1600x1200
                - 1360x768
                - 1280x1024
                - 1280x960
                - 1280x720
                - 1024x768
                - 800x600
                - 720x576
                - 720x480
                - 640x480
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--persistent"
            - "--format=yuyv"
            - "--resolution={resolution}"
            - "--desired-fps={desired_fps}"
            - "--drop-same-frames=30"
            - "--unix={unix}"
            - "--unix-rm"
            - "--unix-mode=0660"
            - "--exit-on-parent-death"
            - "--process-name-prefix={process_name_prefix}"
            - "--notify-parent"
            - "--no-log-colors"
            - "--jpeg-sink=kvmd::ustreamer::jpeg"
            - "--jpeg-sink-mode=0660"
```
